### ISSUE TITLE
Daily Log 2021-09-07

### ISSUE THREAD

**Issue by dave-ohouse** [dave-ohouse/dailylog#1]
# Daily Log 2021-09-07

## ✅  TODO
- [x] 11:30 스크럼
- [ ] IntelliJ setup
- [ ] docker 설치
- [ ] flyway cli 설치
- [ ] node 설치
- [ ] yarn 설치
- [ ] ohouse-logistics 클론, 빌드 테스트
- [ ] 셋업 가이드 작성(?)

**Comment by dave-ohouse** [comment]
노을님 미팅 정리

질문들
- Jira 사용법
- branch 전략
- 배포 싸이클?
